services:
  - type: web
    name: musicmanager
    env: docker
    plan: free
    branch: main
    buildCommand: ""
    startCommand: "php artisan serve --host 0.0.0.0 --port 10000"
    healthCheckPath: /
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_KEY
        sync: false
      - key: DB_CONNECTION
        value: mysql
      - key: DB_HOST
        sync: false
      - key: DB_PORT
        value: 3306
      - key: DB_DATABASE
        sync: false
      - key: DB_USERNAME
        sync: false
      - key: DB_PASSWORD
        sync: false
